CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR(20) PRIMARY KEY,
    MEMBER_PW VARCHAR(20) NOT NULL,
    MEMBER_NAME VARCHAR(20) NOT NULL,
    MEMBER_GRADE VARCHAR(10) NOT NULL,
    MEMBER_AGE INT NOT NULL
);
INSERT INTO MEMBER(MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_GRADE, MEMBER_AGE) VALUES('admin','1234','관리자','ADMIN',30);

CREATE TABLE PRODUCT(
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(20) NOT NULL,
    PRODUCT_PRICE INT DEFAULT 0,
    PRODUCT_CNT INT DEFAULT 0,
    PRODUCT_INFO VARCHAR(500) NOT NULL
);


CREATE TABLE ORDERLIST(
    ORDERLIST_ID INT PRIMARY KEY,
    MEMBER_ID VARCHAR(20) REFERENCES MEMBER(MEMBER_ID),
    ORDERLIST_DATE DATE
);

CREATE TABLE ORDERLIST_CONTENT(
    ORDERLIST_CONTENT_ID INT PRIMARY KEY,
    ORDERLIST_ID INT REFERENCES ORDERLIST(ORDERLIST_ID),
    PRODUCT_ID INT REFERENCES PRODUCT(PRODUCT_ID),
    ORDERLIST_CONTENT_CNT INT
);

CREATE TABLE CART(
    CART_ID INT PRIMARY KEY,
    MEMBER_ID VARCHAR(20) REFERENCES MEMBER(MEMBER_ID),
    PRODUCT_ID INT REFERENCES PRODUCT(PRODUCT_ID),
    CART_CNT INT
);

CREATE TABLE REVIEW(
    RID INT PRIMARY KEY,
    REGISTED_DATE DATE,
    MID VARCHAR(20) REFERENCES MEMBER(MID),
    CONTENT VARCHAR(200),
    ORDER_NUM INT REFERENCES ORDER_LIST(ORDER_NUM),
    PRODUCT_GRADE INT CHECK(PRODUCT_GRADE BETWEEN 1 AND 5)
);

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CNT FROM PRODUCT
INSERT INTO MEMBER(MID, PW, NAME, GRADE, AGE) VALUES('admin','1234','관리자','ADMIN',30);
INSERT INTO ORDERLIST(ORDER_ID,MEMBER_ID,PRODUCT_ID,PRODUCT_NAME,PRODUCT_CNT,PRODUCT_PRICE,ORDER_DATE,ORDER_NUM) 
VALUES(2,'ari',1001,'BEOPLAY EX FERRARI EDITION',1,649000,'2023-12-28',123124);

DROP TABLE MEMBER;
DROP TABLE PRODUCT;
DROP TABLE CART;
DROP TABLE REVIEW;
DROP TABLE ORDER_LIST;

INSERT INTO MEMBER(MID, PW, NAME, GRADE, AGE) VALUES('user','1234','사용자','USER',20);

SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM CART;
SELECT * FROM MEMBER WHERE MID='admin'
SELECT *
FROM ORDERLIST O 
    INNER JOIN 
        (SELECT  OC.ORDERLIST_CONTENT_ID , OC.ORDERLIST_CONTENT_CNT , OC.ORDERLIST_ID , OC.PRODUCT_ID , P.PRODUCT_NAME , P.PRODUCT_CATEGORY , P.PRODUCT_PRICE , P.PRODUCT_INFO 
        FROM ORDERLIST_CONTENT OC INNER JOIN PRODUCT P ON P.PRODUCT_ID = OC.PRODUCT_ID) OBJ 
        ON O.ORDERLIST_ID = OBJ.ORDERLIST_ID
    INNER JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID



UPDATE MEMBER SET AGE=26 WHERE MID='user';
UPDATE MEMBER SET PW=1234, NAME='박현민', AGE=27 WHERE MID='user';



