CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(30) NOT NULL,
	WRITER VARCHAR(15) NOT NULL,
	CONTENT VARCHAR(50) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE
);

INSERT INTO BOARD (BID,TITLE,WRITER,CONTENT) VALUES((SELECT NVL(MAX(BID),10) + 1 FROM BOARD),'제목','admin','내용');

SELECT * FROM BOARD;

DROP TABLE BOARD;