CREATE TABLE MEMBER(
	MID VARCHAR(15) PRIMARY KEY,
	MPW VARCHAR(10) NOT NULL,
	NAME VARCHAR(15) NOT NULL
);

INSERT INTO MEMBER VALUES('teemo','1234','작은티모');
INSERT INTO MEMBER VALUES('admin','1234','관리자');

SELECT * FROM MEMBER;

DROP TABLE MEMBER;