-- 주석
CREATE TABLE PRODUCT (
	PID 	INT				PRIMARY KEY,
	NAME 	VARCHAR(15)		NOT NULL,
	PRICE 	INT,
	CNT 	INT				DEFAULT 10
);

DROP TABLE PRODUCT;

INSERT INTO PRODUCT VALUES(1, '콜라', 1100, 1);
INSERT INTO PRODUCT VALUES(2, '사이다', 1200, 3);
INSERT INTO PRODUCT (PID, NAME, PRICE) VALUES(3, '환타', 1500);
INSERT INTO PRODUCT VALUES(4, '환타포도', 1500,0);
INSERT INTO PRODUCT VALUES(SELECT NVL(MAX(PID),1000)+1, '환타포도', 1500,0);

SELECT * FROM PRODUCT;
SELECT PID FROM PRODUCT;
SELECT PID FROM PRODUCT WHERE PID>=2;
SELECT PID FROM PRODUCT ORDER BY PRICE DESC;
SELECT PID,NAME FROM PRODUCT WHERE NAME LIKE '%환타%';

UPDATE PRODUCT SET CNT=10 WHERE PID = 1;
UPDATE PRODUCT SET CNT=CNT-1 WHERE PID = 1;


DELETE FROM PRODUCT WHERE PID=1004;